local ParticleConfig = {}

ParticleConfig.Heights = {
	InnerSRing = 125,
	RightOuterSRing = 175,
	LeftOuterSRing = 175,
	SS = 230, 
	InnerMSRing = 50,
	OuterMSRing = 175, 
	InnerORing = 175,
	OuterORing = 50,
	UpperRightCRing = 30,
	LowerRightCRing = 30, 
	UpperLeftCRing = 30, 
	LowerLeftCRing = 30,
	L2 = 50,
	A1 = 30,
	A2 = 30,
	A3 = 30,
	A4 = 30,
	A5 = 30,
	A6 = 30,
	A7 = 30,
	A8 = 30,
	L1 = 80
}

ParticleConfig.DefaultPulseTimes = {
	InnerSRing = 1,
	RightOuterSRing = 1,
	LeftOuterSRing = 1,
	SS = 2,
	InnerMSRing = 2,
	OuterMSRing = 2,
	InnerORing = 2,
	OuterORing = 1,
	C = 1,
	L2 = 1,
	L1 = 1,
	UpperRightCRing = 1,
	LowerRightCRing = 1, 
	UpperLeftCRing = 1, 
	LowerLeftCRing = 1,
}

return ParticleConfig
